--- # provisioning/roles/nodered/tasks/main.yml

  - name: install node-red globally
    become: no
    shell: sudo npm install -g node-red # intentional sudo
#   args:
#     creates: /usr/bin/node-red
    tags:
      - nodered

  - name: add modules to Node Red
    become: no
    npm:
      name: "{{ item }}"
      path: "{{ nodered_home }}"  
    with_items:
      - https://github.com/ELL-i/node-red-contrib-coap.git
      - node-red-contrib-fsm
      - node-red-node-google
      - node-red-dashboard
      - node-red-contrib-boolean-logic
      - https://github.com/ELL-i/node-red-contrib-nordpool.git
    tags:
      - nodered

  - name: add templated nodered to systemd started services
    template:
      src: "nodered.service.j2"
      dest:  "{{ nodered_service_unit_path  }}"
      owner: "{{ nodered_service_unit_owner }}"
      group: "{{ nodered_service_unit_group }}"
      mode:  "{{ nodered_service_unit_mode  }}"
    tags:
      - nodered


  - name: systemctl daemon-reload after new unit file
    shell: systemctl daemon-reload
    tags:
      - nodered
      
  - name: enable nodered unit
    shell: systemctl enable nodered.service
    tags:
      - nodered
      
