package com.avob.openadr.server.common.vtn.models.venmarketcontext;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.avob.openadr.server.common.vtn.models.ItemBase;

@Entity
@Table(name = "venmarketcontextreport")
public class VenMarketContextReport {

	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@NotNull
	private String reportName;

	@NotNull
	private String reportType;

	@NotNull
	private String readingType;

	@NotNull
	private String payloadBase;

	private ItemBase itemBase;

	/**
	 * Related market context
	 */
	@ManyToOne
	@JoinColumn(name = "venmarketcontext_id")
	private VenMarketContext venMarketContext;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getReportType() {
		return reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public String getReadingType() {
		return readingType;
	}

	public void setReadingType(String readingType) {
		this.readingType = readingType;
	}

	public String getPayloadBase() {
		return payloadBase;
	}

	public void setPayloadBase(String payloadBase) {
		this.payloadBase = payloadBase;
	}

	public ItemBase getItemBase() {
		return itemBase;
	}

	public void setItemBase(ItemBase itemBase) {
		this.itemBase = itemBase;
	}

	public VenMarketContext getVenMarketContext() {
		return venMarketContext;
	}

	public void setVenMarketContext(VenMarketContext venMarketContext) {
		this.venMarketContext = venMarketContext;
	}

}
