---
  - name: Add group 'oadr-vtn20b' 
    group:
      name: oadr-vtn20b
      state: present

  - name: Add user 'oadr-vtn20b'
    user:
      name: oadr-vtn20b
      groups: oadr-vtn20b
      append: yes
      comment: "oadr-vtn20b User"
      state: present

  - name: Creates app lib folder
    file:
      path: /opt/oadr-vtn20b/lib
      state: directory
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Creates app cert folder
    file:
      path: /opt/oadr-vtn20b/cert
      state: directory
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Creates app log folder
    file:
      path: /var/log/oadr-vtn20b
      state: directory
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Creates app pid folder
    file:
      path: /var/run/oadr-vtn20b
      state: directory
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Creates app pid folder (bis)
    file:
      path: /var/run/oadr-vtn20b_optoadr-vtn20b
      state: directory
      owner: oadr-vtn20b
      group: oadr-vtn20b






  - name: Copy cert folder
    copy:
      src: ../../../cert/
      dest: /opt/oadr-vtn20b/cert/
      owner: oadr-vtn20b
      group: oadr-vtn20b

