# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "vtn20b"

  # # forward RabbitMQ ampq
  config.vm.network "forwarded_port", guest: 5671, host: 5671

  # forward RabbitMQ Admin UI
  config.vm.network "forwarded_port", guest: 15672, host: 15672

  # forward NodeRed Dashboard
  config.vm.network "forwarded_port", guest: 1880, host: 1880

  # forward Openfire XMPP
  config.vm.network "forwarded_port", guest: 5222, host: 5222

    # forward VTN20b HTTP
  # config.vm.network "forwarded_port", guest: 8181, host: 8181

  # config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.33.2"

  

  config.vm.provider :virtualbox do |v|
    v.name = "vtn.oadr.com"
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end



  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :vtn20b do |vtn|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = 'v'
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    # ansible.inventory_path = "provisioning/inventory"
    ansible.galaxy_role_file = 'requirements.yml'
    ansible.become = true
    ansible.groups = {
      "web" => ["vtn20b"]
    }
  end

end


