package com.avob.openadr.server.common.vtn.models.demandresponseevent;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.avob.openadr.server.common.vtn.models.ItemBase;

@Entity
@Table(name = "demandresponseeventbaseline")
public class DemandResponseEventBaseline {
	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@ElementCollection
	@LazyCollection(LazyCollectionOption.FALSE)
	private List<DemandResponseEventSignalInterval> intervals;

	@Column(name = "baselineStart")
	private Long start;

	@Column(name = "baselineDuration")
	private String duration;

	@NotNull
	private String baselineId;

	@ElementCollection
	@LazyCollection(LazyCollectionOption.FALSE)
	private List<String> resourceId;

	private String baselineName;

	@Column(name = "baselineItemBase")
	private ItemBase itemBase;

	public List<DemandResponseEventSignalInterval> getIntervals() {
		return intervals;
	}

	public void setIntervals(List<DemandResponseEventSignalInterval> intervals) {
		this.intervals = intervals;
	}

	public Long getStart() {
		return start;
	}

	public void setStart(Long start) {
		this.start = start;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getBaselineId() {
		return baselineId;
	}

	public void setBaselineId(String baselineId) {
		this.baselineId = baselineId;
	}

	public List<String> getResourceId() {
		return resourceId;
	}

	public void setResourceId(List<String> resourceId) {
		this.resourceId = resourceId;
	}

	public String getBaselineName() {
		return baselineName;
	}

	public void setBaselineName(String baselineName) {
		this.baselineName = baselineName;
	}

	public ItemBase getItemBase() {
		return itemBase;
	}

	public void setItemBase(ItemBase itemBase) {
		this.itemBase = itemBase;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}
