package com.avob.openadr.server.common.vtn.models.demandresponseevent;

import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.avob.openadr.server.common.vtn.models.vendemandresponseevent.VenDemandResponseEvent;

/**
 * An entity of DemandResponseEvent
 * 
 * @author bertrand
 *
 */
@Entity
@Table(name = "demandresponseevent")
public class DemandResponseEvent {

	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@NotNull
	@Column(unique = true)
	private String eventId;

	@NotNull
	@Enumerated(EnumType.STRING)
	private DemandResponseEventOadrProfileEnum oadrProfile;

	@NotNull
	private Long createdTimestamp = System.currentTimeMillis();

	private Long lastUpdateTimestamp;

	@NotNull
	@Enumerated(EnumType.STRING)
	private DemandResponseEventStateEnum state = DemandResponseEventStateEnum.ACTIVE;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event", cascade = CascadeType.REMOVE)
	private List<VenDemandResponseEvent> venDemandResponseEvent;

	private long modificationNumber = 0;

	private DemandResponseEventDescriptor descriptor;

	private DemandResponseEventActivePeriod activePeriod;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event", cascade = CascadeType.ALL)
	private Set<DemandResponseEventSignal> signals;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public DemandResponseEventStateEnum getState() {
		return state;
	}

	public void setState(DemandResponseEventStateEnum state) {
		this.state = state;
	}

	public Long getCreatedTimestamp() {
		return createdTimestamp;
	}

	public void setCreatedTimestamp(Long createdTimestamp) {
		this.createdTimestamp = createdTimestamp;
	}

	public Long getLastUpdateTimestamp() {
		return lastUpdateTimestamp;
	}

	public void setLastUpdateTimestamp(Long lastUpdateTimestamp) {
		this.lastUpdateTimestamp = lastUpdateTimestamp;
	}

	public long getModificationNumber() {
		return modificationNumber;
	}

	public void setModificationNumber(long modificationNumber) {
		this.modificationNumber = modificationNumber;
	}

	public DemandResponseEventOadrProfileEnum getOadrProfile() {
		return oadrProfile;
	}

	public void setOadrProfile(DemandResponseEventOadrProfileEnum oadrProfile) {
		this.oadrProfile = oadrProfile;
	}

	public String getEventId() {
		return eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public DemandResponseEventDescriptor getDescriptor() {
		if (descriptor == null) {
			descriptor = new DemandResponseEventDescriptor();
		}
		return descriptor;
	}

	public void setDescriptor(DemandResponseEventDescriptor descriptor) {
		this.descriptor = descriptor;
	}

	public DemandResponseEventActivePeriod getActivePeriod() {
		if (activePeriod == null) {
			activePeriod = new DemandResponseEventActivePeriod();
		}
		return activePeriod;
	}

	public void setActivePeriod(DemandResponseEventActivePeriod activePeriod) {
		this.activePeriod = activePeriod;
	}

	public Set<DemandResponseEventSignal> getSignals() {
		return signals;
	}

	public void setSignals(Set<DemandResponseEventSignal> signals) {
		this.signals = signals;
	}

}
