package com.avob.openadr.server.common.vtn.models.demandresponseevent;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.avob.openadr.server.common.vtn.models.vendemandresponseevent.VenDemandResponseEvent;
import com.avob.openadr.server.common.vtn.models.venmarketcontext.VenMarketContext;

/**
 * An entity of DemandResponseEvent
 * 
 * @author bertrand
 *
 */
@Entity
@Table(name = "demandresponseevent")
public class DemandResponseEvent {

    /**
     * Autogenerated unique id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(unique = true)
    private String eventId;

    @NotNull
    @Enumerated(EnumType.STRING)
    private DemandResponseEventOadrProfileEnum oadrProfile;

    @NotNull
    private Long start;

    private Long end;

    @NotNull
    private Long startNotification;

    /**
     * Event active state duration as xml duration
     */
    @NotNull
    private String duration;

    /**
     * Event notification duration as xml duration
     */
    @NotNull
    private String notificationDuration;

    /**
     * Event tolerance as xml duration
     */
    private String toleranceDuration;

    /**
     * Event ramp up duration as xml duration
     */
    private String rampUpDuration;

    /**
     * Event recovery duration as xml duration
     */
    private String recoveryDuration;

    @NotNull
    private Long createdTimestamp = System.currentTimeMillis();

    private Long lastUpdateTimestamp;

    @ManyToOne
    @NotNull
    private VenMarketContext marketContext;

    private String comaSeparatedTargetedVenUsername;

    @Enumerated(EnumType.STRING)
    private DemandResponseEventSimpleValueEnum value;

    @NotNull
    @Enumerated(EnumType.STRING)
    private DemandResponseEventStateEnum state = DemandResponseEventStateEnum.ACTIVE;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event", cascade = CascadeType.REMOVE)
    private List<VenDemandResponseEvent> venDemandResponseEvent;

    private long modificationNumber = 0;

    private long priority = 0;

    private boolean testEvent = false;

    private String vtnComment;

    @Lob
    private String event;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public DemandResponseEventStateEnum getState() {
        return state;
    }

    public void setState(DemandResponseEventStateEnum state) {
        this.state = state;
    }

    public DemandResponseEventSimpleValueEnum getValue() {
        return value;
    }

    public void setValue(DemandResponseEventSimpleValueEnum value) {
        this.value = value;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public VenMarketContext getMarketContext() {
        return marketContext;
    }

    public void setMarketContext(VenMarketContext marketContext) {
        this.marketContext = marketContext;
    }

    public Long getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(Long createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    public Long getLastUpdateTimestamp() {
        return lastUpdateTimestamp;
    }

    public void setLastUpdateTimestamp(Long lastUpdateTimestamp) {
        this.lastUpdateTimestamp = lastUpdateTimestamp;
    }

    public long getModificationNumber() {
        return modificationNumber;
    }

    public void setModificationNumber(long modificationNumber) {
        this.modificationNumber = modificationNumber;
    }

    public String getComaSeparatedTargetedVenUsername() {
        return comaSeparatedTargetedVenUsername;
    }

    public void setComaSeparatedTargetedVenUsername(String comaSeparatedTargetedVenUsername) {
        this.comaSeparatedTargetedVenUsername = comaSeparatedTargetedVenUsername;
    }

    public long getPriority() {
        return priority;
    }

    public void setPriority(long priority) {
        this.priority = priority;
    }

    public String getToleranceDuration() {
        return toleranceDuration;
    }

    public void setToleranceDuration(String toleranceDuration) {
        this.toleranceDuration = toleranceDuration;
    }

    public String getRampUpDuration() {
        return rampUpDuration;
    }

    public void setRampUpDuration(String rampUpDuration) {
        this.rampUpDuration = rampUpDuration;
    }

    public String getRecoveryDuration() {
        return recoveryDuration;
    }

    public void setRecoveryDuration(String recoveryDuration) {
        this.recoveryDuration = recoveryDuration;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public boolean isTestEvent() {
        return testEvent;
    }

    public void setTestEvent(boolean testEvent) {
        this.testEvent = testEvent;
    }

    public String getNotificationDuration() {
        return notificationDuration;
    }

    public void setNotificationDuration(String notificationDuration) {
        this.notificationDuration = notificationDuration;
    }

    public Long getStartNotification() {
        return startNotification;
    }

    public void setStartNotification(Long startNotification) {
        this.startNotification = startNotification;
    }

    public String getVtnComment() {
        return vtnComment;
    }

    public void setVtnComment(String vtnComment) {
        this.vtnComment = vtnComment;
    }

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public DemandResponseEventOadrProfileEnum getOadrProfile() {
        return oadrProfile;
    }

    public void setOadrProfile(DemandResponseEventOadrProfileEnum oadrProfile) {
        this.oadrProfile = oadrProfile;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

}
