# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "nodered"
  # config.vm.network "forwarded_port", guest: 8181, host: 8181
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 1880, host: 1880

  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  config.vm.synced_folder "./node-red-contrib-oadr-ven", "/home/vagrant/node-red-contrib-oadr-ven"

  

  config.vm.provider :virtualbox do |v|
    v.name = "nodered"
    v.memory = 1024
    v.cpus = 1
    # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # v.customize ["modifyvm", :id, "--ioapic", "on"]
  end



  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"
   # config.vm.network :private_network, ip: "192.168.33.27"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :nodered do |vtn|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = 'v'
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = true
    ansible.groups = {
      "web" => ["nodered"]
    }
  end

end


