package com.avob.openadr.server.oadr20b.vtn.models.venpoll;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.avob.openadr.server.common.vtn.models.ven.Ven;

/**
 * 
 * @author bertrand
 *
 */
@Entity
@Table(name = "venpoll")
public class VenPoll {

    /**
     * Autogenerated unique id
     */

    private long id;

    /**
     * Related ven
     */
    private Ven ven;

    private Long createdTimestamp;

    private String message;

    public VenPoll() {
    }

    public VenPoll(Ven ven, String message) {
        this.ven = ven;
        this.message = message;
        this.createdTimestamp = System.currentTimeMillis();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne
    @JoinColumn(name = "ven_id")
    public Ven getVen() {
        return ven;
    }

    public void setVen(Ven ven) {
        this.ven = ven;
    }

    @Lob
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(Long createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

}
