/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.api;

import com.avob.server.oadrvtn20b.handler.ApiException;
import com.avob.server.oadrvtn20b.model.AbstractUserWithRoleDto;
import com.avob.server.oadrvtn20b.model.InputStreamResource;
import com.avob.server.oadrvtn20b.model.OadrAppCreateDto;
import com.avob.server.oadrvtn20b.model.OadrAppDto;
import com.avob.server.oadrvtn20b.model.OadrUserCreateDto;
import com.avob.server.oadrvtn20b.model.OadrUserDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountControllerApi
 */
@Ignore
public class AccountControllerApiTest {

    private final AccountControllerApi api = new AccountControllerApi();

    
    /**
     * createApp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAppUsingPOSTTest() throws ApiException {
        OadrAppCreateDto dto = null;
        InputStreamResource response = api.createAppUsingPOST(dto);

        // TODO: test validations
    }
    
    /**
     * createUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserUsingPOSTTest() throws ApiException {
        OadrUserCreateDto dto = null;
        InputStreamResource response = api.createUserUsingPOST(dto);

        // TODO: test validations
    }
    
    /**
     * deleteApp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAppUsingDELETETest() throws ApiException {
        String username = null;
        api.deleteAppUsingDELETE(username);

        // TODO: test validations
    }
    
    /**
     * deleteUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserUsingDELETETest() throws ApiException {
        String username = null;
        api.deleteUserUsingDELETE(username);

        // TODO: test validations
    }
    
    /**
     * listApp
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAppUsingGETTest() throws ApiException {
        List<OadrAppDto> response = api.listAppUsingGET();

        // TODO: test validations
    }
    
    /**
     * listUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUserUsingGETTest() throws ApiException {
        List<OadrUserDto> response = api.listUserUsingGET();

        // TODO: test validations
    }
    
    /**
     * registeredUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registeredUserUsingGETTest() throws ApiException {
        String name = null;
        AbstractUserWithRoleDto response = api.registeredUserUsingGET(name);

        // TODO: test validations
    }
    
}
