/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.api;

import com.avob.server.oadrvtn20b.handler.ApiException;
import com.avob.server.oadrvtn20b.model.VenGroupDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupControllerApi
 */
@Ignore
public class GroupControllerApiTest {

    private final GroupControllerApi api = new GroupControllerApi();

    
    /**
     * createGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupUsingPOSTTest() throws ApiException {
        VenGroupDto dto = null;
        VenGroupDto response = api.createGroupUsingPOST(dto);

        // TODO: test validations
    }
    
    /**
     * deleteGroupById
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupByIdUsingDELETETest() throws ApiException {
        Long groupId = null;
        api.deleteGroupByIdUsingDELETE(groupId);

        // TODO: test validations
    }
    
    /**
     * findGroupByName
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findGroupByNameUsingGETTest() throws ApiException {
        String groupName = null;
        VenGroupDto response = api.findGroupByNameUsingGET(groupName);

        // TODO: test validations
    }
    
    /**
     * listGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGroupUsingGETTest() throws ApiException {
        List<VenGroupDto> response = api.listGroupUsingGET();

        // TODO: test validations
    }
    
    /**
     * updateGroup
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGroupUsingPUTTest() throws ApiException {
        VenGroupDto dto = null;
        VenGroupDto response = api.updateGroupUsingPUT(dto);

        // TODO: test validations
    }
    
}
