/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.api;

import com.avob.server.oadrvtn20b.handler.ApiException;
import com.avob.server.oadrvtn20b.model.ReportCapabilityDescriptionDto;
import com.avob.server.oadrvtn20b.model.ReportCapabilityDto;
import com.avob.server.oadrvtn20b.model.ReportRequestDto;
import com.avob.server.oadrvtn20b.model.VtnConfigurationDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Oadr20bVtnControllerApi
 */
@Ignore
public class Oadr20bVtnControllerApiTest {

    private final Oadr20bVtnControllerApi api = new Oadr20bVtnControllerApi();

    
    /**
     * viewConf
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void viewConfUsingGETTest() throws ApiException {
        VtnConfigurationDto response = api.viewConfUsingGET();

        // TODO: test validations
    }
    
    /**
     * viewOtherReportCapabilityDescription
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void viewOtherReportCapabilityDescriptionUsingGET1Test() throws ApiException {
        String reportSpecifierId = null;
        List<ReportCapabilityDescriptionDto> response = api.viewOtherReportCapabilityDescriptionUsingGET1(reportSpecifierId);

        // TODO: test validations
    }
    
    /**
     * viewReportRequest
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void viewReportRequestUsingGET1Test() throws ApiException {
        List<ReportRequestDto> response = api.viewReportRequestUsingGET1();

        // TODO: test validations
    }
    
    /**
     * viewSelfReportCapability
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void viewSelfReportCapabilityUsingGETTest() throws ApiException {
        List<ReportCapabilityDto> response = api.viewSelfReportCapabilityUsingGET();

        // TODO: test validations
    }
    
}
