/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.api;

import com.avob.server.oadrvtn20b.handler.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoleControllerApi
 */
@Ignore
public class RoleControllerApiTest {

    private final RoleControllerApi api = new RoleControllerApi();

    
    /**
     * getUserRole
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserRoleUsingPOSTTest() throws ApiException {
        String username = null;
        List<String> response = api.getUserRoleUsingPOST(username);

        // TODO: test validations
    }
    
}
