---
  - name: Download postgres connector jar
    get_url:
      url: https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
      dest: /opt/oadr-vtn20b/lib/postgresql-42.2.5.jar
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Install loader.properties
    template:
      src: templates/loader.properties
      dest: /opt/oadr-vtn20b/loader.properties
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Install log4j2.xml
    template:
      src: templates/log4j2.xml
      dest: /opt/oadr-vtn20b/log4j2.xml
      owner: oadr-vtn20b
      group: oadr-vtn20b

  - name: Set oadr-vtn20b.conf permission
    file: 
      path:  /opt/oadr-vtn20b/oadr-vtn20b.conf
      owner: oadr-vtn20b
      group: oadr-vtn20b
      state: touch
      mode: 0400

  - name: Install oadr-vtn20b.jar 
    copy:
      src: ../../../OpenADRServerVTN20b/target/OpenADRServerVTN20b-0.1.0-SNAPSHOT.jar
      dest: /opt/oadr-vtn20b/oadr-vtn20b.jar

  - name: Set oadr-vtn20b.jar permission 
    file: 
      path:  /opt/oadr-vtn20b/oadr-vtn20b.jar
      owner: oadr-vtn20b
      group: oadr-vtn20b
      state: touch
      mode: 0500

  # - name: Install oadr-vtn20b.service
  #   template:
  #     src: templates/oadr-vtn20b.service
  #     dest: /etc/systemd/system/oadr-vtn20b.service
  #     owner: oadr-vtn20b
  #     group: oadr-vtn20b

  - name: Restart oadr-vtn20b application
    command: /bin/true
    notify:
    - restart oadr-vtn20b
