export const LOAD_VTN_CONFIGURATION = 'LOAD_VTN_CONFIGURATION';
export const LOAD_VTN_CONFIGURATION_SUCCESS = 'LOAD_VTN_CONFIGURATION_SUCCESS';
export const LOAD_VTN_CONFIGURATION_ERROR = 'LOAD_VTN_CONFIGURATION_ERROR';

export const LOAD_MARKET_CONTEXT = 'LOAD_MARKET_CONTEXT';
export const LOAD_MARKET_CONTEXT_SUCCESS = 'LOAD_MARKET_CONTEXT_SUCCESS';
export const LOAD_MARKET_CONTEXT_ERROR = 'LOAD_MARKET_CONTEXT_ERROR';

export const CREATE_MARKET_CONTEXT = 'CREATE_MARKET_CONTEXT';
export const CREATE_MARKET_CONTEXT_SUCCESS = 'CREATE_MARKET_CONTEXT_SUCCESS';
export const CREATE_MARKET_CONTEXT_ERROR = 'CREATE_MARKET_CONTEXT_ERROR';