// VTN CONFIGURATION
export const LOAD_VTN_CONFIGURATION = 'LOAD_VTN_CONFIGURATION';
export const LOAD_VTN_CONFIGURATION_SUCCESS = 'LOAD_VTN_CONFIGURATION_SUCCESS';
export const LOAD_VTN_CONFIGURATION_ERROR = 'LOAD_VTN_CONFIGURATION_ERROR';

export const LOAD_MARKET_CONTEXT = 'LOAD_MARKET_CONTEXT';
export const LOAD_MARKET_CONTEXT_SUCCESS = 'LOAD_MARKET_CONTEXT_SUCCESS';
export const LOAD_MARKET_CONTEXT_ERROR = 'LOAD_MARKET_CONTEXT_ERROR';

export const CREATE_MARKET_CONTEXT = 'CREATE_MARKET_CONTEXT';
export const CREATE_MARKET_CONTEXT_SUCCESS = 'CREATE_MARKET_CONTEXT_SUCCESS';
export const CREATE_MARKET_CONTEXT_ERROR = 'CREATE_MARKET_CONTEXT_ERROR';

export const DELETE_MARKET_CONTEXT = 'DELETE_MARKET_CONTEXT';
export const DELETE_MARKET_CONTEXT_SUCCESS = 'DELETE_MARKET_CONTEXT_SUCCESS';
export const DELETE_MARKET_CONTEXT_ERROR = 'DELETE_MARKET_CONTEXT_ERROR';

export const LOAD_GROUP = 'LOAD_GROUP';
export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
export const LOAD_GROUP_ERROR = 'LOAD_GROUP_ERROR';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const DELETE_GROUP = 'DELETE_GROUP';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

// VEN
export const LOAD_VEN = 'LOAD_VEN';
export const LOAD_VEN_SUCCESS = 'LOAD_VEN_SUCCESS';
export const LOAD_VEN_ERROR = 'LOAD_VEN_ERROR';

export const LOAD_VEN_DETAIL = 'LOAD_VEN_DETAIL';
export const LOAD_VEN_DETAIL_SUCCESS = 'LOAD_VEN_DETAIL_SUCCESS';
export const LOAD_VEN_DETAIL_ERROR = 'LOAD_VEN_DETAIL_ERROR';
