---
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: 'update'
      raw: sudo apt-get update
    # - name: 'upgrade'
    #   raw: sudo apt-get -y upgrade
    - name: 'install python2'
      raw: sudo apt-get -y install python zip 
    ### JAVA 8
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Install Oracle Java 8
      become: yes
      apt:
        pkg:
          - openjdk-8-jre-headless
          - ca-certificates
        state: present


  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Add the inventory into /etc/hosts
      become: true
      blockinfile:
        dest: /etc/hosts
        content: "{{ lookup('template', 'templates/hosts.j2') }}"
        state: present

    

  handlers:

  roles:
    - ../../roles/common
    # - geerlingguy.apache
    # - ../../roles/nodejs
    # - ../../roles/nodered
    # - ../../roles/nodered-oadr-ven
    - ../../roles/oadr-common
    - ../../roles/oadr-postgresql
    - ../../roles/oadr-rabbitmq
    - ../../roles/oadr-openfire
    - ../../roles/oadr-vtn20b
