---
- hosts: all
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: 'update'
      raw: sudo apt-get update
    - name: 'upgrade'
      raw: sudo apt-get -y upgrade
    - name: 'install python2'
      raw: sudo apt-get -y install python

  vars_files:
    - vars/main.yml

  tasks:
    - name: Add the user 'oadr-vtn20b'
      user:
        name: oadr-vtn20b
        groups: oadr-vtn20b
        shell: /sbin/nologin
        append: yes
        comment: "oadr-vtn20b nologin User"
        state: present

    - name: Creates app lib folder
      file:
        path: /opt/oadr-vtn20b/lib
        state: directory
        owner: oadr-vtn20b
        group: oadr-vtn20b

    - name: Creates app cert folder
      file:
        path: /opt/oadr-vtn20b/cert
        state: directory
        owner: oadr-vtn20b
        group: oadr-vtn20b

    - name: Creates app log folder
      file:
        path: /var/log/oadr-vtn20b
        state: directory
        owner: oadr-vtn20b
        group: oadr-vtn20b

    - name: Creates app pid folder
      file:
        path: /var/run/oadr-vtn20b
        state: directory
        owner: oadr-vtn20b
        group: oadr-vtn20b


    - name: Copy cert folder
      copy:
        src: ../../../cert
        dest: /opt/oadr-vtn20b
        owner: oadr-vtn20b
        group: oadr-vtn20b
    
    - name: Download postgres connector jar
      get_url:
        url: https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
        dest: /opt/oadr-vtn20b/lib/postgresql-42.2.5.jar
        owner: oadr-vtn20b
        group: oadr-vtn20b

    - name: Install loader.properties
      template:
        src: templates/loader.properties
        dest: /opt/oadr-vtn20b/loader.properties
        owner: oadr-vtn20b

    - name: Start service oadr-vtn20b, if not started
      service:
        name: oadr-vtn20b
        state: started

  roles:
    - ansiblebit.oracle-java
    - geerlingguy.postgresql
    - remyma.ansible-springboot
