---
- src: ansiblebit.oracle-java
- src: geerlingguy.postgresql
- src: geerlingguy.rabbitmq
- src: https://github.com/Sjnahak/ansible-springboot.git
  name: remyma.ansible-springboot
- src: geerlingguy.apache