package com.avob.openadr.server.oadr20b.vtn.models.venreport.capability;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

import com.avob.openadr.model.oadr20b.ei.ReportNameEnumeratedType;

/**
 * 
 * @author bzanni
 *
 */
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class ReportCapability {

	/**
	 * Autogenerated unique id
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long id;

	private String reportSpecifierId;

	private String reportId;

	@Enumerated(EnumType.STRING)
	private ReportNameEnumeratedType reportName;

	private Long createdDatetime;

	private String duration;

	private Long start;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getReportSpecifierId() {
		return reportSpecifierId;
	}

	public void setReportSpecifierId(String reportSpecifierId) {
		this.reportSpecifierId = reportSpecifierId;
	}

	public ReportNameEnumeratedType getReportName() {
		return reportName;
	}

	public void setReportName(ReportNameEnumeratedType reportName) {
		this.reportName = reportName;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public Long getCreatedDatetime() {
		return createdDatetime;
	}

	public void setCreatedDatetime(Long createDatetime) {
		this.createdDatetime = createDatetime;
	}

	public String getReportId() {
		return reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	public Long getStart() {
		return start;
	}

	public void setStart(Long start) {
		this.start = start;
	}

}
