---
  - name: Install node-gyp build dependencies
    when: ( ansible_os_family  == "Debian" )
    apt:
      name: build-essential
      state: present

  - name: Ansible check file exists example.
    stat:
      path: /home/vagrant/node-red-contrib-oadr-ven
    register: repo

  - name: Git clone node-red-contrib-oadr-ven module
    git:
      repo: 'https://github.com/avob/node-red-contrib-oadr-ven'
      dest: /home/vagrant/node-red-contrib-oadr-ven
      force: yes
    when: repo.stat.exists == false

  # - name: Set oadr-vtn20b.conf permission
  #   file: 
  #     path: /home/vagrant/node-red-contrib-oadr-ven
  #     state: directory
  #     mode: 0777
  #     recurse: yes

  # - name: Install node-red-contrib-oadr-ven
  #   shell:  sudo npm install
  #   become: no
  #   args:
  #     chdir: /home/vagrant/node-red-contrib-oadr-ven 

  # - name: Add node-red-contrib-oadr-ven module to nodered
  #   shell:  sudo npm install
  #   become: no
  #   args:
  #     chdir: /home/vagrant/.node-red

  # - name: Add node-red-contrib-oadr-ven module to nodered
  #   shell:  sudo npm install ../node-red-contrib-oadr-ven
  #   become: no
  #   args:
  #     chdir: /home/vagrant/.node-red

  - name: Install node-red-contrib-oadr-ven
    npm:
      path: /home/vagrant/node-red-contrib-oadr-ven 
      executable: /usr/bin/npm --unsafe-perm=true --allow-root

  - name: Install node-red
    npm:
      path: /home/vagrant/.node-red
      executable: /usr/bin/npm --unsafe-perm=true --allow-root

  - name: Add node-red-contrib-oadr-ven module to nodered
    npm:
      name: ../node-red-contrib-oadr-ven
      path: /home/vagrant/.node-red

  # - npm:
  #   executable: /usr/bin/npm --unsafe-perm=true --allow-root

  - name: Install example flow
    copy:
      src: files/flows_default.json
      dest: /home/vagrant/.node-red/flows_{{ansible_hostname}}.json

  - name: Get venId
    shell: "cat /opt/oadr-vtn20b/cert/ven1.oadr.com.fingerprint"
    register: venId

  - name: Inject venIdinto flow
    shell: "sed -i 's/%VEN_ID%/{{ venId.stdout }}/g' /home/vagrant/.node-red/flows_{{ansible_hostname}}.json"



  - name: Recursively change ownership of a directory
    file:
      path: /home/vagrant/.node-red
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant

  - name: start nodered from unit
    shell: systemctl restart nodered 
