---
  - name: Install node-gyp build dependencies
    when: ( ansible_os_family  == "Debian" )
    apt: name={{item}} state=installed
    with_items:
      - build-essential

  - name: Git clone node-red-contrib-oadr-ven module
    git:
      repo: 'https://github.com/avob/node-red-contrib-oadr-ven'
      dest: /home/vagrant/node-red-contrib-oadr-ven
      force: yes

  - name: Set oadr-vtn20b.conf permission
    file: 
      path: /home/vagrant/node-red-contrib-oadr-ven
      owner: vagrant
      group: vagrant
      state: directory
      mode: 0777
      recurse: yes

  - name: Install node-red-contrib-oadr-ven
    shell: sudo npm install
    become: no
    args:
      chdir: /home/vagrant/node-red-contrib-oadr-ven 

  - name: Add node-red-contrib-oadr-ven module to nodered
    shell: sudo npm install
    become: no
    args:
      chdir: /home/vagrant/.node-red

  - name: Add node-red-contrib-oadr-ven module to nodered
    shell: sudo npm install ../node-red-contrib-oadr-ven
    become: no
    args:
      chdir: /home/vagrant/.node-red




  - name: Install example flow
    copy:
      src: files/flows_default.json
      dest: /home/vagrant/.node-red/flows_{{ansible_hostname}}.json

  - name: start nodered from unit
    shell: systemctl restart nodered 
