# POSTGRES CONF
postgresql_databases:
  - name: oadr-vtn20b
  - name: oadr-openfire

postgresql_users:
  - name: oadr-vtn20b
    password: supersecure
  - name: oadr-openfire
    password: supersecure

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
  - { type: host, database: oadr-vtn20b, user: oadr-vtn20b, address: '127.0.0.1/32', auth_method: md5 }
  - { type: host, database: oadr-openfire, user: oadr-openfire, address: '127.0.0.1/32', auth_method: md5 }

# RABBITMQ
rabbitmq_daemon: rabbitmq-server
rabbitmq_state: started
rabbitmq_enabled: true
rabbitmq_version: "3.6.16"
# rabbitmq_version: "3.7.14" investigate python rabbitmq mismatch erlang dependecies

# OADRVTN SPRING BOOT APP CONF
springboot_application_name: oadr-vtn20b
springboot_src_file: ../../../OpenADRServerVTN20b/target/OpenADRServerVTN20b-0.0.1-SNAPSHOT.jar
springboot_propertyfile_template: templates/application.properties
springboot_configuration_template: templates/oadr-vtn20b.conf
springboot_user: oadr-vtn20b
springboot_group: oadr-vtn20b
