// react router location change
export const LOCATION_CHANGE = "@@router/LOCATION_CHANGE"

// VTN CONFIGURATION
export const LOAD_VTN_CONFIGURATION = 'LOAD_VTN_CONFIGURATION';
export const LOAD_VTN_CONFIGURATION_SUCCESS = 'LOAD_VTN_CONFIGURATION_SUCCESS';
export const LOAD_VTN_CONFIGURATION_ERROR = 'LOAD_VTN_CONFIGURATION_ERROR';

export const LOAD_MARKET_CONTEXT = 'LOAD_MARKET_CONTEXT';
export const LOAD_MARKET_CONTEXT_SUCCESS = 'LOAD_MARKET_CONTEXT_SUCCESS';
export const LOAD_MARKET_CONTEXT_ERROR = 'LOAD_MARKET_CONTEXT_ERROR';

export const CREATE_MARKET_CONTEXT = 'CREATE_MARKET_CONTEXT';
export const CREATE_MARKET_CONTEXT_SUCCESS = 'CREATE_MARKET_CONTEXT_SUCCESS';
export const CREATE_MARKET_CONTEXT_ERROR = 'CREATE_MARKET_CONTEXT_ERROR';

export const DELETE_MARKET_CONTEXT = 'DELETE_MARKET_CONTEXT';
export const DELETE_MARKET_CONTEXT_SUCCESS = 'DELETE_MARKET_CONTEXT_SUCCESS';
export const DELETE_MARKET_CONTEXT_ERROR = 'DELETE_MARKET_CONTEXT_ERROR';

export const LOAD_GROUP = 'LOAD_GROUP';
export const LOAD_GROUP_SUCCESS = 'LOAD_GROUP_SUCCESS';
export const LOAD_GROUP_ERROR = 'LOAD_GROUP_ERROR';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const DELETE_GROUP = 'DELETE_GROUP';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

// VEN
export const LOAD_VEN = 'LOAD_VEN';
export const LOAD_VEN_SUCCESS = 'LOAD_VEN_SUCCESS';
export const LOAD_VEN_ERROR = 'LOAD_VEN_ERROR';

export const SEARCH_VEN = 'SEARCH_VEN';
export const SEARCH_VEN_SUCCESS = 'SEARCH_VEN_SUCCESS';
export const SEARCH_VEN_ERROR = 'SEARCH_VEN_ERROR';

export const LOAD_VEN_DETAIL = 'LOAD_VEN_DETAIL';
export const LOAD_VEN_DETAIL_SUCCESS = 'LOAD_VEN_DETAIL_SUCCESS';
export const LOAD_VEN_DETAIL_ERROR = 'LOAD_VEN_DETAIL_ERROR';

export const CREATE_VEN = 'CREATE_VEN';
export const CREATE_VEN_SUCCESS = 'CREATE_VEN_SUCCESS';
export const CREATE_VEN_ERROR = 'CREATE_VEN_ERROR';

export const DELETE_VEN = 'DELETE_VEN';
export const DELETE_VEN_SUCCESS = 'DELETE_VEN_SUCCESS';
export const DELETE_VEN_ERROR = 'DELETE_VEN_ERROR';

export const LOAD_VEN_MARKET_CONTEXT = 'LOAD_VEN_MARKET_CONTEXT';
export const LOAD_VEN_MARKET_CONTEXT_SUCCESS = 'LOAD_VEN_MARKET_CONTEXT_SUCCESS';
export const LOAD_VEN_MARKET_CONTEXT_ERROR = 'LOAD_VEN_MARKET_CONTEXT_ERROR';

export const LOAD_VEN_GROUP = 'LOAD_VEN_GROUP';
export const LOAD_VEN_GROUP_SUCCESS = 'LOAD_VEN_GROUP_SUCCESS';
export const LOAD_VEN_GROUP_ERROR = 'LOAD_VEN_GROUP_ERROR';

export const ADD_VEN_MARKET_CONTEXT = 'ADD_VEN_MARKET_CONTEXT';
export const ADD_VEN_MARKET_CONTEXT_SUCCESS = 'ADD_VEN_MARKET_CONTEXT_SUCCESS';
export const ADD_VEN_MARKET_CONTEXT_ERROR = 'ADD_VEN_MARKET_CONTEXT_ERROR';

export const REMOVE_VEN_MARKET_CONTEXT = 'REMOVE_VEN_MARKET_CONTEXT';
export const REMOVE_VEN_MARKET_CONTEXT_SUCCESS = 'REMOVE_VEN_MARKET_CONTEXT_SUCCESS';
export const REMOVE_VEN_MARKET_CONTEXT_ERROR = 'REMOVE_VEN_MARKET_CONTEXT_ERROR';

export const ADD_VEN_GROUP = 'ADD_VEN_GROUP';
export const ADD_VEN_GROUP_SUCCESS = 'ADD_VEN_GROUP_SUCCESS';
export const ADD_VEN_GROUP_ERROR = 'ADD_VEN_GROUP_ERROR';

export const REMOVE_VEN_GROUP = 'REMOVE_VEN_GROUP';
export const REMOVE_VEN_GROUP_SUCCESS = 'REMOVE_VEN_GROUP_SUCCESS';
export const REMOVE_VEN_GROUP_ERROR = 'REMOVE_VEN_GROUP_ERROR';

export const REQUEST_REREGISTRATION_VEN = 'REQUEST_REREGISTRATION_VEN';
export const REQUEST_REREGISTRATION_VEN_SUCCESS = 'REQUEST_REREGISTRATION_VEN_SUCCESS';
export const REQUEST_REREGISTRATION_VEN_ERROR = 'REQUEST_REREGISTRATION_VEN_ERROR';

export const REQUEST_CANCEL_REGISTRATION_VEN = 'REQUEST_CANCEL_REGISTRATION_VEN';
export const REQUEST_CANCEL_REGISTRATION_VEN_SUCCESS = 'REQUEST_CANCEL_REGISTRATION_VEN_SUCCESS';
export const REQUEST_CANCEL_REGISTRATION_VEN_ERROR = 'REQUEST_CANCEL_REGISTRATION_VEN_ERROR';

export const REQUEST_CLEAN_REGISTRATION_VEN = 'REQUEST_CLEAN_REGISTRATION_VEN';
export const REQUEST_CLEAN_REGISTRATION_VEN_SUCCESS = 'REQUEST_CLEAN_REGISTRATION_VEN_SUCCESS';
export const REQUEST_CLEAN_REGISTRATION_VEN_ERROR = 'REQUEST_CLEAN_REGISTRATION_VEN_ERROR';

export const LOAD_VEN_AVAILABLE_REPORT = 'LOAD_VEN_AVAILABLE_REPORT';
export const LOAD_VEN_AVAILABLE_REPORT_SUCCESS = 'LOAD_VEN_AVAILABLE_REPORT_SUCCESS';
export const LOAD_VEN_AVAILABLE_REPORT_ERROR = 'LOAD_VEN_AVAILABLE_REPORT_VEN_ERROR';

export const LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION = 'LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION';
export const LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION_SUCCESS = 'LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION_SUCCESS';
export const LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION_ERROR = 'LOAD_VEN_AVAILABLE_REPORT_DESCRIPTION_ERROR';

export const LOAD_VEN_REQUESTED_REPORT = 'LOAD_VEN_REQUESTED_REPORT';
export const LOAD_VEN_REQUESTED_REPORT_SUCCESS = 'LOAD_VEN_REQUESTED_REPORT_SUCCESS';
export const LOAD_VEN_REQUESTED_REPORT_ERROR = 'LOAD_VEN_REQUESTED_REPORT_ERROR';

export const LOAD_VEN_REQUESTED_REPORT_SPECIFIER = 'LOAD_VEN_REQUESTED_REPORT_SPECIFIER';
export const LOAD_VEN_REQUESTED_REPORT_SPECIFIER_SUCCESS = 'LOAD_VEN_REQUESTED_REPORT_SPECIFIER_SUCCESS';
export const LOAD_VEN_REQUESTED_REPORT_SPECIFIER_ERROR = 'LOAD_VEN_REQUESTED_REPORT_SPECIFIER_ERROR';




export const REQUEST_VEN_REGISTER_REPORT = 'REQUEST_VEN_REGISTER_REPORT';
export const REQUEST_VEN_REGISTER_REPORT_SUCCESS = 'REQUEST_VEN_REGISTER_REPORT_SUCCESS';
export const REQUEST_VEN_REGISTER_REPORT_ERROR = 'REQUEST_VEN_REGISTER_REPORT_ERROR';

export const SEND_VTN_REGISTER_REPORT = 'SEND_VTN_REGISTER_REPORT';
export const SEND_VTN_REGISTER_REPORT_SUCCESS = 'SEND_VTN_REGISTER_REPORT_SUCCESS';
export const SEND_VTN_REGISTER_REPORT_ERROR = 'SEND_VTN_REGISTER_REPORT_ERROR';

export const CREATE_REQUESTED_REPORT = 'CREATE_REQUESTED_REPORT';
export const CREATE_REQUESTED_REPORT_SUCCESS = 'CREATE_REQUESTED_REPORT_SUCCESS';
export const CREATE_REQUESTED_REPORT_ERROR = 'CREATE_REQUESTED_REPORT_ERROR';

export const CANCEL_REQUESTED_REPORT = 'CANCEL_REQUESTED_REPORT';
export const CANCEL_REQUESTED_REPORT_SUCCESS = 'CANCEL_REQUESTED_REPORT_SUCCESS';
export const CANCEL_REQUESTED_REPORT_ERROR = 'CANCEL_REQUESTED_REPORT_ERROR';

export const LOAD_VEN_OPT = 'LOAD_VEN_OPT';
export const LOAD_VEN_OPT_SUCCESS = 'LOAD_VEN_OPT_SUCCESS';
export const LOAD_VEN_OPT_ERROR = 'LOAD_VEN_OPT_ERROR';

// EVENTS
export const LOAD_EVENT = 'LOAD_EVENT';
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS';
export const LOAD_EVENT_ERROR = 'LOAD_EVENT_ERROR';

export const SEARCH_EVENT = 'SEARCH_EVENT';
export const SEARCH_EVENT_SUCCESS = 'SEARCH_EVENT_SUCCESS';
export const SEARCH_EVENT_ERROR = 'SEARCH_EVENT_ERROR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const LOAD_EVENT_DETAIL = 'LOAD_EVENT_DETAIL';
export const LOAD_EVENT_DETAIL_SUCCESS = 'LOAD_EVENT_DETAIL_SUCCESS';
export const LOAD_EVENT_DETAIL_ERROR = 'LOAD_EVENT_DETAIL_ERROR';

export const PUBLISH_EVENT = 'PUBLISH_EVENT';
export const PUBLISH_EVENT_SUCCESS = 'PUBLISH_EVENT_SUCCESS';
export const PUBLISH_EVENT_ERROR = 'PUBLISH_EVENT_ERROR';

export const ACTIVE_EVENT = 'ACTIVE_EVENT';
export const ACTIVE_EVENT_SUCCESS = 'ACTIVE_EVENT_SUCCESS';
export const ACTIVE_EVENT_ERROR = 'ACTIVE_EVENT_ERROR';

export const CANCEL_EVENT = 'CANCEL_EVENT';
export const CANCEL_EVENT_SUCCESS = 'CANCEL_EVENT_SUCCESS';
export const CANCEL_EVENT_ERROR = 'CANCEL_EVENT_ERROR';

export const LOAD_EVENT_VEN_RESPONSE = 'LOAD_EVENT_VEN_RESPONSE';
export const LOAD_EVENT_VEN_RESPONSE_SUCCESS = 'LOAD_EVENT_VEN_RESPONSE_SUCCESS';
export const LOAD_EVENT_VEN_RESPONSE_ERROR = 'LOAD_EVENT_VEN_RESPONSE_ERROR';

// ACCOUNT
export const LOAD_ACCOUNT_USER = 'LOAD_ACCOUNT_USER';
export const LOAD_ACCOUNT_USER_SUCCESS = 'LOAD_ACCOUNT_USER_SUCCESS';
export const LOAD_ACCOUNT_USER_ERROR = 'LOAD_ACCOUNT_USER_ERROR';

export const LOAD_ACCOUNT_APP = 'LOAD_ACCOUNT_APP';
export const LOAD_ACCOUNT_APP_SUCCESS = 'LOAD_ACCOUNT_APP_SUCCESS';
export const LOAD_ACCOUNT_APP_ERROR = 'LOAD_ACCOUNT_APP_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const CREATE_APP = 'CREATE_APP';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const CREATE_APP_ERROR = 'CREATE_APP_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const DELETE_APP = 'DELETE_APP';
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export const DELETE_APP_ERROR = 'DELETE_APP_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';













