/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.avob.server.oadrvtn20b.model.DemandResponseEventActivePeriodDto;
import com.avob.server.oadrvtn20b.model.DemandResponseEventDescriptorDto;
import com.avob.server.oadrvtn20b.model.DemandResponseEventSignalDto;
import com.avob.server.oadrvtn20b.model.DemandResponseEventTargetDto;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * DemandResponseEventCreateDto
 */

public class DemandResponseEventCreateDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("activePeriod")
  private DemandResponseEventActivePeriodDto activePeriod = null;

  @SerializedName("descriptor")
  private DemandResponseEventDescriptorDto descriptor = null;

  @SerializedName("published")
  private Boolean published = null;

  @SerializedName("signals")
  private List<DemandResponseEventSignalDto> signals = new ArrayList<DemandResponseEventSignalDto>();

  @SerializedName("targets")
  private List<DemandResponseEventTargetDto> targets = new ArrayList<DemandResponseEventTargetDto>();

  public DemandResponseEventCreateDto activePeriod(DemandResponseEventActivePeriodDto activePeriod) {
    this.activePeriod = activePeriod;
    return this;
  }

   /**
   * Get activePeriod
   * @return activePeriod
  **/
  @ApiModelProperty(example = "null", value = "")
  public DemandResponseEventActivePeriodDto getActivePeriod() {
    return activePeriod;
  }

  public void setActivePeriod(DemandResponseEventActivePeriodDto activePeriod) {
    this.activePeriod = activePeriod;
  }

  public DemandResponseEventCreateDto descriptor(DemandResponseEventDescriptorDto descriptor) {
    this.descriptor = descriptor;
    return this;
  }

   /**
   * Get descriptor
   * @return descriptor
  **/
  @ApiModelProperty(example = "null", value = "")
  public DemandResponseEventDescriptorDto getDescriptor() {
    return descriptor;
  }

  public void setDescriptor(DemandResponseEventDescriptorDto descriptor) {
    this.descriptor = descriptor;
  }

  public DemandResponseEventCreateDto published(Boolean published) {
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPublished() {
    return published;
  }

  public void setPublished(Boolean published) {
    this.published = published;
  }

  public DemandResponseEventCreateDto signals(List<DemandResponseEventSignalDto> signals) {
    this.signals = signals;
    return this;
  }

  public DemandResponseEventCreateDto addSignalsItem(DemandResponseEventSignalDto signalsItem) {
    this.signals.add(signalsItem);
    return this;
  }

   /**
   * Get signals
   * @return signals
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DemandResponseEventSignalDto> getSignals() {
    return signals;
  }

  public void setSignals(List<DemandResponseEventSignalDto> signals) {
    this.signals = signals;
  }

  public DemandResponseEventCreateDto targets(List<DemandResponseEventTargetDto> targets) {
    this.targets = targets;
    return this;
  }

  public DemandResponseEventCreateDto addTargetsItem(DemandResponseEventTargetDto targetsItem) {
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * Get targets
   * @return targets
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DemandResponseEventTargetDto> getTargets() {
    return targets;
  }

  public void setTargets(List<DemandResponseEventTargetDto> targets) {
    this.targets = targets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemandResponseEventCreateDto demandResponseEventCreateDto = (DemandResponseEventCreateDto) o;
    return Objects.equals(this.activePeriod, demandResponseEventCreateDto.activePeriod) &&
        Objects.equals(this.descriptor, demandResponseEventCreateDto.descriptor) &&
        Objects.equals(this.published, demandResponseEventCreateDto.published) &&
        Objects.equals(this.signals, demandResponseEventCreateDto.signals) &&
        Objects.equals(this.targets, demandResponseEventCreateDto.targets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activePeriod, descriptor, published, signals, targets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemandResponseEventCreateDto {\n");
    
    sb.append("    activePeriod: ").append(toIndentedString(activePeriod)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    signals: ").append(toIndentedString(signals)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

