/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.avob.server.oadrvtn20b.model.DemandResponseEventSignalIntervalDto;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * DemandResponseEventSignalDto
 */

public class DemandResponseEventSignalDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("currentValue")
  private Float currentValue = null;

  @SerializedName("intervals")
  private List<DemandResponseEventSignalIntervalDto> intervals = new ArrayList<DemandResponseEventSignalIntervalDto>();

  @SerializedName("signalName")
  private String signalName = null;

  @SerializedName("signalType")
  private String signalType = null;

  @SerializedName("unitType")
  private String unitType = null;

  public DemandResponseEventSignalDto currentValue(Float currentValue) {
    this.currentValue = currentValue;
    return this;
  }

   /**
   * Get currentValue
   * @return currentValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getCurrentValue() {
    return currentValue;
  }

  public void setCurrentValue(Float currentValue) {
    this.currentValue = currentValue;
  }

  public DemandResponseEventSignalDto intervals(List<DemandResponseEventSignalIntervalDto> intervals) {
    this.intervals = intervals;
    return this;
  }

  public DemandResponseEventSignalDto addIntervalsItem(DemandResponseEventSignalIntervalDto intervalsItem) {
    this.intervals.add(intervalsItem);
    return this;
  }

   /**
   * Get intervals
   * @return intervals
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DemandResponseEventSignalIntervalDto> getIntervals() {
    return intervals;
  }

  public void setIntervals(List<DemandResponseEventSignalIntervalDto> intervals) {
    this.intervals = intervals;
  }

  public DemandResponseEventSignalDto signalName(String signalName) {
    this.signalName = signalName;
    return this;
  }

   /**
   * Get signalName
   * @return signalName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSignalName() {
    return signalName;
  }

  public void setSignalName(String signalName) {
    this.signalName = signalName;
  }

  public DemandResponseEventSignalDto signalType(String signalType) {
    this.signalType = signalType;
    return this;
  }

   /**
   * Get signalType
   * @return signalType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSignalType() {
    return signalType;
  }

  public void setSignalType(String signalType) {
    this.signalType = signalType;
  }

  public DemandResponseEventSignalDto unitType(String unitType) {
    this.unitType = unitType;
    return this;
  }

   /**
   * Get unitType
   * @return unitType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUnitType() {
    return unitType;
  }

  public void setUnitType(String unitType) {
    this.unitType = unitType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemandResponseEventSignalDto demandResponseEventSignalDto = (DemandResponseEventSignalDto) o;
    return Objects.equals(this.currentValue, demandResponseEventSignalDto.currentValue) &&
        Objects.equals(this.intervals, demandResponseEventSignalDto.intervals) &&
        Objects.equals(this.signalName, demandResponseEventSignalDto.signalName) &&
        Objects.equals(this.signalType, demandResponseEventSignalDto.signalType) &&
        Objects.equals(this.unitType, demandResponseEventSignalDto.unitType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentValue, intervals, signalName, signalType, unitType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemandResponseEventSignalDto {\n");
    
    sb.append("    currentValue: ").append(toIndentedString(currentValue)).append("\n");
    sb.append("    intervals: ").append(toIndentedString(intervals)).append("\n");
    sb.append("    signalName: ").append(toIndentedString(signalName)).append("\n");
    sb.append("    signalType: ").append(toIndentedString(signalType)).append("\n");
    sb.append("    unitType: ").append(toIndentedString(unitType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

