/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.avob.server.oadrvtn20b.model.DemandResponseEventSignalDto;
import com.avob.server.oadrvtn20b.model.DemandResponseEventTargetDto;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * DemandResponseEventUpdateDto
 */

public class DemandResponseEventUpdateDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("published")
  private Boolean published = null;

  @SerializedName("signals")
  private List<DemandResponseEventSignalDto> signals = new ArrayList<DemandResponseEventSignalDto>();

  @SerializedName("targets")
  private List<DemandResponseEventTargetDto> targets = new ArrayList<DemandResponseEventTargetDto>();

  public DemandResponseEventUpdateDto published(Boolean published) {
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPublished() {
    return published;
  }

  public void setPublished(Boolean published) {
    this.published = published;
  }

  public DemandResponseEventUpdateDto signals(List<DemandResponseEventSignalDto> signals) {
    this.signals = signals;
    return this;
  }

  public DemandResponseEventUpdateDto addSignalsItem(DemandResponseEventSignalDto signalsItem) {
    this.signals.add(signalsItem);
    return this;
  }

   /**
   * Get signals
   * @return signals
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DemandResponseEventSignalDto> getSignals() {
    return signals;
  }

  public void setSignals(List<DemandResponseEventSignalDto> signals) {
    this.signals = signals;
  }

  public DemandResponseEventUpdateDto targets(List<DemandResponseEventTargetDto> targets) {
    this.targets = targets;
    return this;
  }

  public DemandResponseEventUpdateDto addTargetsItem(DemandResponseEventTargetDto targetsItem) {
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * Get targets
   * @return targets
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DemandResponseEventTargetDto> getTargets() {
    return targets;
  }

  public void setTargets(List<DemandResponseEventTargetDto> targets) {
    this.targets = targets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DemandResponseEventUpdateDto demandResponseEventUpdateDto = (DemandResponseEventUpdateDto) o;
    return Objects.equals(this.published, demandResponseEventUpdateDto.published) &&
        Objects.equals(this.signals, demandResponseEventUpdateDto.signals) &&
        Objects.equals(this.targets, demandResponseEventUpdateDto.targets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(published, signals, targets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DemandResponseEventUpdateDto {\n");
    
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    signals: ").append(toIndentedString(signals)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

