/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * OadrAppCreateDto
 */

public class OadrAppCreateDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("authenticationType")
  private String authenticationType = null;

  @SerializedName("commonName")
  private String commonName = null;

  @SerializedName("needCertificateGeneration")
  private String needCertificateGeneration = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("roles")
  private List<String> roles = new ArrayList<String>();

  @SerializedName("username")
  private String username = null;

  public OadrAppCreateDto authenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
    return this;
  }

   /**
   * Get authenticationType
   * @return authenticationType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAuthenticationType() {
    return authenticationType;
  }

  public void setAuthenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
  }

  public OadrAppCreateDto commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

   /**
   * Get commonName
   * @return commonName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public OadrAppCreateDto needCertificateGeneration(String needCertificateGeneration) {
    this.needCertificateGeneration = needCertificateGeneration;
    return this;
  }

   /**
   * Get needCertificateGeneration
   * @return needCertificateGeneration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNeedCertificateGeneration() {
    return needCertificateGeneration;
  }

  public void setNeedCertificateGeneration(String needCertificateGeneration) {
    this.needCertificateGeneration = needCertificateGeneration;
  }

  public OadrAppCreateDto password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public OadrAppCreateDto roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public OadrAppCreateDto addRolesItem(String rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRoles() {
    return roles;
  }

  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public OadrAppCreateDto username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OadrAppCreateDto oadrAppCreateDto = (OadrAppCreateDto) o;
    return Objects.equals(this.authenticationType, oadrAppCreateDto.authenticationType) &&
        Objects.equals(this.commonName, oadrAppCreateDto.commonName) &&
        Objects.equals(this.needCertificateGeneration, oadrAppCreateDto.needCertificateGeneration) &&
        Objects.equals(this.password, oadrAppCreateDto.password) &&
        Objects.equals(this.roles, oadrAppCreateDto.roles) &&
        Objects.equals(this.username, oadrAppCreateDto.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationType, commonName, needCertificateGeneration, password, roles, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OadrAppCreateDto {\n");
    
    sb.append("    authenticationType: ").append(toIndentedString(authenticationType)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    needCertificateGeneration: ").append(toIndentedString(needCertificateGeneration)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

