/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.io.Serializable;

/**
 * OtherReportRequestDtoCreateSubscriptionDto
 */

public class OtherReportRequestDtoCreateSubscriptionDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("granularity")
  private String granularity = null;

  @SerializedName("reportBackDuration")
  private String reportBackDuration = null;

  @SerializedName("reportSpecifierId")
  private String reportSpecifierId = null;

  @SerializedName("rid")
  private Map<String, Boolean> rid = new HashMap<String, Boolean>();

  public OtherReportRequestDtoCreateSubscriptionDto granularity(String granularity) {
    this.granularity = granularity;
    return this;
  }

   /**
   * Get granularity
   * @return granularity
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGranularity() {
    return granularity;
  }

  public void setGranularity(String granularity) {
    this.granularity = granularity;
  }

  public OtherReportRequestDtoCreateSubscriptionDto reportBackDuration(String reportBackDuration) {
    this.reportBackDuration = reportBackDuration;
    return this;
  }

   /**
   * Get reportBackDuration
   * @return reportBackDuration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportBackDuration() {
    return reportBackDuration;
  }

  public void setReportBackDuration(String reportBackDuration) {
    this.reportBackDuration = reportBackDuration;
  }

  public OtherReportRequestDtoCreateSubscriptionDto reportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
    return this;
  }

   /**
   * Get reportSpecifierId
   * @return reportSpecifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportSpecifierId() {
    return reportSpecifierId;
  }

  public void setReportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
  }

  public OtherReportRequestDtoCreateSubscriptionDto rid(Map<String, Boolean> rid) {
    this.rid = rid;
    return this;
  }

  public OtherReportRequestDtoCreateSubscriptionDto putRidItem(String key, Boolean ridItem) {
    this.rid.put(key, ridItem);
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Boolean> getRid() {
    return rid;
  }

  public void setRid(Map<String, Boolean> rid) {
    this.rid = rid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherReportRequestDtoCreateSubscriptionDto otherReportRequestDtoCreateSubscriptionDto = (OtherReportRequestDtoCreateSubscriptionDto) o;
    return Objects.equals(this.granularity, otherReportRequestDtoCreateSubscriptionDto.granularity) &&
        Objects.equals(this.reportBackDuration, otherReportRequestDtoCreateSubscriptionDto.reportBackDuration) &&
        Objects.equals(this.reportSpecifierId, otherReportRequestDtoCreateSubscriptionDto.reportSpecifierId) &&
        Objects.equals(this.rid, otherReportRequestDtoCreateSubscriptionDto.rid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(granularity, reportBackDuration, reportSpecifierId, rid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherReportRequestDtoCreateSubscriptionDto {\n");
    
    sb.append("    granularity: ").append(toIndentedString(granularity)).append("\n");
    sb.append("    reportBackDuration: ").append(toIndentedString(reportBackDuration)).append("\n");
    sb.append("    reportSpecifierId: ").append(toIndentedString(reportSpecifierId)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

