/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * OtherReportRequestDtoCreateRequestDto
 */

public class OtherReportRequestDtoCreateRequestDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("end")
  private Long end = null;

  @SerializedName("reportSpecifierId")
  private String reportSpecifierId = null;

  @SerializedName("rid")
  private List<String> rid = new ArrayList<String>();

  @SerializedName("start")
  private Long start = null;

  public OtherReportRequestDtoCreateRequestDto end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public OtherReportRequestDtoCreateRequestDto reportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
    return this;
  }

   /**
   * Get reportSpecifierId
   * @return reportSpecifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportSpecifierId() {
    return reportSpecifierId;
  }

  public void setReportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
  }

  public OtherReportRequestDtoCreateRequestDto rid(List<String> rid) {
    this.rid = rid;
    return this;
  }

  public OtherReportRequestDtoCreateRequestDto addRidItem(String ridItem) {
    this.rid.add(ridItem);
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getRid() {
    return rid;
  }

  public void setRid(List<String> rid) {
    this.rid = rid;
  }

  public OtherReportRequestDtoCreateRequestDto start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherReportRequestDtoCreateRequestDto otherReportRequestDtoCreateRequestDto = (OtherReportRequestDtoCreateRequestDto) o;
    return Objects.equals(this.end, otherReportRequestDtoCreateRequestDto.end) &&
        Objects.equals(this.reportSpecifierId, otherReportRequestDtoCreateRequestDto.reportSpecifierId) &&
        Objects.equals(this.rid, otherReportRequestDtoCreateRequestDto.rid) &&
        Objects.equals(this.start, otherReportRequestDtoCreateRequestDto.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end, reportSpecifierId, rid, start);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherReportRequestDtoCreateRequestDto {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    reportSpecifierId: ").append(toIndentedString(reportSpecifierId)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

