/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.avob.server.oadrvtn20b.model.KeyTokenType;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * OtherReportDataKeyTokenDto
 */

public class OtherReportDataKeyTokenDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("accuracy")
  private Float accuracy = null;

  @SerializedName("confidence")
  private Long confidence = null;

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("reportSpecifierId")
  private String reportSpecifierId = null;

  @SerializedName("rid")
  private String rid = null;

  @SerializedName("start")
  private Long start = null;

  @SerializedName("tokens")
  private List<KeyTokenType> tokens = new ArrayList<KeyTokenType>();

  public OtherReportDataKeyTokenDto accuracy(Float accuracy) {
    this.accuracy = accuracy;
    return this;
  }

   /**
   * Get accuracy
   * @return accuracy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getAccuracy() {
    return accuracy;
  }

  public void setAccuracy(Float accuracy) {
    this.accuracy = accuracy;
  }

  public OtherReportDataKeyTokenDto confidence(Long confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getConfidence() {
    return confidence;
  }

  public void setConfidence(Long confidence) {
    this.confidence = confidence;
  }

  public OtherReportDataKeyTokenDto duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public OtherReportDataKeyTokenDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OtherReportDataKeyTokenDto reportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
    return this;
  }

   /**
   * Get reportSpecifierId
   * @return reportSpecifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportSpecifierId() {
    return reportSpecifierId;
  }

  public void setReportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
  }

  public OtherReportDataKeyTokenDto rid(String rid) {
    this.rid = rid;
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRid() {
    return rid;
  }

  public void setRid(String rid) {
    this.rid = rid;
  }

  public OtherReportDataKeyTokenDto start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public OtherReportDataKeyTokenDto tokens(List<KeyTokenType> tokens) {
    this.tokens = tokens;
    return this;
  }

  public OtherReportDataKeyTokenDto addTokensItem(KeyTokenType tokensItem) {
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Get tokens
   * @return tokens
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<KeyTokenType> getTokens() {
    return tokens;
  }

  public void setTokens(List<KeyTokenType> tokens) {
    this.tokens = tokens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherReportDataKeyTokenDto otherReportDataKeyTokenDto = (OtherReportDataKeyTokenDto) o;
    return Objects.equals(this.accuracy, otherReportDataKeyTokenDto.accuracy) &&
        Objects.equals(this.confidence, otherReportDataKeyTokenDto.confidence) &&
        Objects.equals(this.duration, otherReportDataKeyTokenDto.duration) &&
        Objects.equals(this.id, otherReportDataKeyTokenDto.id) &&
        Objects.equals(this.reportSpecifierId, otherReportDataKeyTokenDto.reportSpecifierId) &&
        Objects.equals(this.rid, otherReportDataKeyTokenDto.rid) &&
        Objects.equals(this.start, otherReportDataKeyTokenDto.start) &&
        Objects.equals(this.tokens, otherReportDataKeyTokenDto.tokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accuracy, confidence, duration, id, reportSpecifierId, rid, start, tokens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherReportDataKeyTokenDto {\n");
    
    sb.append("    accuracy: ").append(toIndentedString(accuracy)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reportSpecifierId: ").append(toIndentedString(reportSpecifierId)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

