/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * OtherReportRequestSpecifierDto
 */

public class OtherReportRequestSpecifierDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("archived")
  private Boolean archived = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("lastUpdateDatetime")
  private Long lastUpdateDatetime = null;

  @SerializedName("lastUpdateValue")
  private String lastUpdateValue = null;

  @SerializedName("reportRequestId")
  private String reportRequestId = null;

  @SerializedName("reportSpecifierId")
  private String reportSpecifierId = null;

  @SerializedName("rid")
  private String rid = null;

  public OtherReportRequestSpecifierDto archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public OtherReportRequestSpecifierDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OtherReportRequestSpecifierDto lastUpdateDatetime(Long lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(Long lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }

  public OtherReportRequestSpecifierDto lastUpdateValue(String lastUpdateValue) {
    this.lastUpdateValue = lastUpdateValue;
    return this;
  }

   /**
   * Get lastUpdateValue
   * @return lastUpdateValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastUpdateValue() {
    return lastUpdateValue;
  }

  public void setLastUpdateValue(String lastUpdateValue) {
    this.lastUpdateValue = lastUpdateValue;
  }

  public OtherReportRequestSpecifierDto reportRequestId(String reportRequestId) {
    this.reportRequestId = reportRequestId;
    return this;
  }

   /**
   * Get reportRequestId
   * @return reportRequestId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportRequestId() {
    return reportRequestId;
  }

  public void setReportRequestId(String reportRequestId) {
    this.reportRequestId = reportRequestId;
  }

  public OtherReportRequestSpecifierDto reportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
    return this;
  }

   /**
   * Get reportSpecifierId
   * @return reportSpecifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportSpecifierId() {
    return reportSpecifierId;
  }

  public void setReportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
  }

  public OtherReportRequestSpecifierDto rid(String rid) {
    this.rid = rid;
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRid() {
    return rid;
  }

  public void setRid(String rid) {
    this.rid = rid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtherReportRequestSpecifierDto otherReportRequestSpecifierDto = (OtherReportRequestSpecifierDto) o;
    return Objects.equals(this.archived, otherReportRequestSpecifierDto.archived) &&
        Objects.equals(this.id, otherReportRequestSpecifierDto.id) &&
        Objects.equals(this.lastUpdateDatetime, otherReportRequestSpecifierDto.lastUpdateDatetime) &&
        Objects.equals(this.lastUpdateValue, otherReportRequestSpecifierDto.lastUpdateValue) &&
        Objects.equals(this.reportRequestId, otherReportRequestSpecifierDto.reportRequestId) &&
        Objects.equals(this.reportSpecifierId, otherReportRequestSpecifierDto.reportSpecifierId) &&
        Objects.equals(this.rid, otherReportRequestSpecifierDto.rid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archived, id, lastUpdateDatetime, lastUpdateValue, reportRequestId, reportSpecifierId, rid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtherReportRequestSpecifierDto {\n");
    
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("    lastUpdateValue: ").append(toIndentedString(lastUpdateValue)).append("\n");
    sb.append("    reportRequestId: ").append(toIndentedString(reportRequestId)).append("\n");
    sb.append("    reportSpecifierId: ").append(toIndentedString(reportSpecifierId)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

