/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * ReportRequestDto
 */

public class ReportRequestDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("acked")
  private Boolean acked = null;

  @SerializedName("createdDatetime")
  private Long createdDatetime = null;

  @SerializedName("end")
  private Long end = null;

  @SerializedName("granularity")
  private String granularity = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("reportBackDuration")
  private String reportBackDuration = null;

  @SerializedName("reportRequestId")
  private String reportRequestId = null;

  @SerializedName("reportSpecifierId")
  private String reportSpecifierId = null;

  @SerializedName("start")
  private Long start = null;

  public ReportRequestDto acked(Boolean acked) {
    this.acked = acked;
    return this;
  }

   /**
   * Get acked
   * @return acked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAcked() {
    return acked;
  }

  public void setAcked(Boolean acked) {
    this.acked = acked;
  }

  public ReportRequestDto createdDatetime(Long createdDatetime) {
    this.createdDatetime = createdDatetime;
    return this;
  }

   /**
   * Get createdDatetime
   * @return createdDatetime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedDatetime() {
    return createdDatetime;
  }

  public void setCreatedDatetime(Long createdDatetime) {
    this.createdDatetime = createdDatetime;
  }

  public ReportRequestDto end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public ReportRequestDto granularity(String granularity) {
    this.granularity = granularity;
    return this;
  }

   /**
   * Get granularity
   * @return granularity
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGranularity() {
    return granularity;
  }

  public void setGranularity(String granularity) {
    this.granularity = granularity;
  }

  public ReportRequestDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ReportRequestDto reportBackDuration(String reportBackDuration) {
    this.reportBackDuration = reportBackDuration;
    return this;
  }

   /**
   * Get reportBackDuration
   * @return reportBackDuration
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportBackDuration() {
    return reportBackDuration;
  }

  public void setReportBackDuration(String reportBackDuration) {
    this.reportBackDuration = reportBackDuration;
  }

  public ReportRequestDto reportRequestId(String reportRequestId) {
    this.reportRequestId = reportRequestId;
    return this;
  }

   /**
   * Get reportRequestId
   * @return reportRequestId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportRequestId() {
    return reportRequestId;
  }

  public void setReportRequestId(String reportRequestId) {
    this.reportRequestId = reportRequestId;
  }

  public ReportRequestDto reportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
    return this;
  }

   /**
   * Get reportSpecifierId
   * @return reportSpecifierId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReportSpecifierId() {
    return reportSpecifierId;
  }

  public void setReportSpecifierId(String reportSpecifierId) {
    this.reportSpecifierId = reportSpecifierId;
  }

  public ReportRequestDto start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportRequestDto reportRequestDto = (ReportRequestDto) o;
    return Objects.equals(this.acked, reportRequestDto.acked) &&
        Objects.equals(this.createdDatetime, reportRequestDto.createdDatetime) &&
        Objects.equals(this.end, reportRequestDto.end) &&
        Objects.equals(this.granularity, reportRequestDto.granularity) &&
        Objects.equals(this.id, reportRequestDto.id) &&
        Objects.equals(this.reportBackDuration, reportRequestDto.reportBackDuration) &&
        Objects.equals(this.reportRequestId, reportRequestDto.reportRequestId) &&
        Objects.equals(this.reportSpecifierId, reportRequestDto.reportSpecifierId) &&
        Objects.equals(this.start, reportRequestDto.start);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acked, createdDatetime, end, granularity, id, reportBackDuration, reportRequestId, reportSpecifierId, start);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportRequestDto {\n");
    
    sb.append("    acked: ").append(toIndentedString(acked)).append("\n");
    sb.append("    createdDatetime: ").append(toIndentedString(createdDatetime)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    granularity: ").append(toIndentedString(granularity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reportBackDuration: ").append(toIndentedString(reportBackDuration)).append("\n");
    sb.append("    reportRequestId: ").append(toIndentedString(reportRequestId)).append("\n");
    sb.append("    reportSpecifierId: ").append(toIndentedString(reportSpecifierId)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

