/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * ReportCapabilityDescriptionDto
 */

public class ReportCapabilityDescriptionDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("itemDescription")
  private String itemDescription = null;

  @SerializedName("itemUnits")
  private String itemUnits = null;

  @SerializedName("oadrMaxPeriod")
  private String oadrMaxPeriod = null;

  @SerializedName("oadrMinPeriod")
  private String oadrMinPeriod = null;

  @SerializedName("oadrOnChange")
  private Boolean oadrOnChange = null;

  /**
   * Gets or Sets readingType
   */
  public enum ReadingTypeEnum {
    @SerializedName("DIRECT_READ")
    DIRECT_READ("DIRECT_READ"),
    
    @SerializedName("NET")
    NET("NET"),
    
    @SerializedName("ALLOCATED")
    ALLOCATED("ALLOCATED"),
    
    @SerializedName("ESTIMATED")
    ESTIMATED("ESTIMATED"),
    
    @SerializedName("SUMMED")
    SUMMED("SUMMED"),
    
    @SerializedName("DERIVED")
    DERIVED("DERIVED"),
    
    @SerializedName("MEAN")
    MEAN("MEAN"),
    
    @SerializedName("PEAK")
    PEAK("PEAK"),
    
    @SerializedName("HYBRID")
    HYBRID("HYBRID"),
    
    @SerializedName("CONTRACT")
    CONTRACT("CONTRACT"),
    
    @SerializedName("PROJECTED")
    PROJECTED("PROJECTED"),
    
    @SerializedName("X_RMS")
    X_RMS("X_RMS"),
    
    @SerializedName("X_NOT_APPLICABLE")
    X_NOT_APPLICABLE("X_NOT_APPLICABLE");

    private String value;

    ReadingTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("readingType")
  private ReadingTypeEnum readingType = null;

  /**
   * Gets or Sets reportType
   */
  public enum ReportTypeEnum {
    @SerializedName("READING")
    READING("READING"),
    
    @SerializedName("USAGE")
    USAGE("USAGE"),
    
    @SerializedName("DEMAND")
    DEMAND("DEMAND"),
    
    @SerializedName("SET_POINT")
    SET_POINT("SET_POINT"),
    
    @SerializedName("DELTA_USAGE")
    DELTA_USAGE("DELTA_USAGE"),
    
    @SerializedName("DELTA_SET_POINT")
    DELTA_SET_POINT("DELTA_SET_POINT"),
    
    @SerializedName("DELTA_DEMAND")
    DELTA_DEMAND("DELTA_DEMAND"),
    
    @SerializedName("BASELINE")
    BASELINE("BASELINE"),
    
    @SerializedName("DEVIATION")
    DEVIATION("DEVIATION"),
    
    @SerializedName("AVG_USAGE")
    AVG_USAGE("AVG_USAGE"),
    
    @SerializedName("AVG_DEMAND")
    AVG_DEMAND("AVG_DEMAND"),
    
    @SerializedName("OPERATING_STATE")
    OPERATING_STATE("OPERATING_STATE"),
    
    @SerializedName("UP_REGULATION_CAPACITY_AVAILABLE")
    UP_REGULATION_CAPACITY_AVAILABLE("UP_REGULATION_CAPACITY_AVAILABLE"),
    
    @SerializedName("DOWN_REGULATION_CAPACITY_AVAILABLE")
    DOWN_REGULATION_CAPACITY_AVAILABLE("DOWN_REGULATION_CAPACITY_AVAILABLE"),
    
    @SerializedName("REGULATION_SETPOINT")
    REGULATION_SETPOINT("REGULATION_SETPOINT"),
    
    @SerializedName("STORED_ENERGY")
    STORED_ENERGY("STORED_ENERGY"),
    
    @SerializedName("TARGET_ENERGY_STORAGE")
    TARGET_ENERGY_STORAGE("TARGET_ENERGY_STORAGE"),
    
    @SerializedName("AVAILABLE_ENERGY_STORAGE")
    AVAILABLE_ENERGY_STORAGE("AVAILABLE_ENERGY_STORAGE"),
    
    @SerializedName("PRICE")
    PRICE("PRICE"),
    
    @SerializedName("LEVEL")
    LEVEL("LEVEL"),
    
    @SerializedName("POWER_FACTOR")
    POWER_FACTOR("POWER_FACTOR"),
    
    @SerializedName("PERCENT_USAGE")
    PERCENT_USAGE("PERCENT_USAGE"),
    
    @SerializedName("PERCENT_DEMAND")
    PERCENT_DEMAND("PERCENT_DEMAND"),
    
    @SerializedName("X_RESOURCE_STATUS")
    X_RESOURCE_STATUS("X_RESOURCE_STATUS");

    private String value;

    ReportTypeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("reportType")
  private ReportTypeEnum reportType = null;

  @SerializedName("rid")
  private String rid = null;

  /**
   * Gets or Sets siScaleCode
   */
  public enum SiScaleCodeEnum {
    @SerializedName("PICO")
    PICO("PICO"),
    
    @SerializedName("NANO")
    NANO("NANO"),
    
    @SerializedName("MICRO")
    MICRO("MICRO"),
    
    @SerializedName("MILLI")
    MILLI("MILLI"),
    
    @SerializedName("CENTI")
    CENTI("CENTI"),
    
    @SerializedName("DECI")
    DECI("DECI"),
    
    @SerializedName("KILO")
    KILO("KILO"),
    
    @SerializedName("MEGA")
    MEGA("MEGA"),
    
    @SerializedName("GIGA")
    GIGA("GIGA"),
    
    @SerializedName("TERA")
    TERA("TERA"),
    
    @SerializedName("NONE")
    NONE("NONE");

    private String value;

    SiScaleCodeEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("siScaleCode")
  private SiScaleCodeEnum siScaleCode = null;

  public ReportCapabilityDescriptionDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ReportCapabilityDescriptionDto itemDescription(String itemDescription) {
    this.itemDescription = itemDescription;
    return this;
  }

   /**
   * Get itemDescription
   * @return itemDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemDescription() {
    return itemDescription;
  }

  public void setItemDescription(String itemDescription) {
    this.itemDescription = itemDescription;
  }

  public ReportCapabilityDescriptionDto itemUnits(String itemUnits) {
    this.itemUnits = itemUnits;
    return this;
  }

   /**
   * Get itemUnits
   * @return itemUnits
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getItemUnits() {
    return itemUnits;
  }

  public void setItemUnits(String itemUnits) {
    this.itemUnits = itemUnits;
  }

  public ReportCapabilityDescriptionDto oadrMaxPeriod(String oadrMaxPeriod) {
    this.oadrMaxPeriod = oadrMaxPeriod;
    return this;
  }

   /**
   * Get oadrMaxPeriod
   * @return oadrMaxPeriod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOadrMaxPeriod() {
    return oadrMaxPeriod;
  }

  public void setOadrMaxPeriod(String oadrMaxPeriod) {
    this.oadrMaxPeriod = oadrMaxPeriod;
  }

  public ReportCapabilityDescriptionDto oadrMinPeriod(String oadrMinPeriod) {
    this.oadrMinPeriod = oadrMinPeriod;
    return this;
  }

   /**
   * Get oadrMinPeriod
   * @return oadrMinPeriod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOadrMinPeriod() {
    return oadrMinPeriod;
  }

  public void setOadrMinPeriod(String oadrMinPeriod) {
    this.oadrMinPeriod = oadrMinPeriod;
  }

  public ReportCapabilityDescriptionDto oadrOnChange(Boolean oadrOnChange) {
    this.oadrOnChange = oadrOnChange;
    return this;
  }

   /**
   * Get oadrOnChange
   * @return oadrOnChange
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOadrOnChange() {
    return oadrOnChange;
  }

  public void setOadrOnChange(Boolean oadrOnChange) {
    this.oadrOnChange = oadrOnChange;
  }

  public ReportCapabilityDescriptionDto readingType(ReadingTypeEnum readingType) {
    this.readingType = readingType;
    return this;
  }

   /**
   * Get readingType
   * @return readingType
  **/
  @ApiModelProperty(example = "null", value = "")
  public ReadingTypeEnum getReadingType() {
    return readingType;
  }

  public void setReadingType(ReadingTypeEnum readingType) {
    this.readingType = readingType;
  }

  public ReportCapabilityDescriptionDto reportType(ReportTypeEnum reportType) {
    this.reportType = reportType;
    return this;
  }

   /**
   * Get reportType
   * @return reportType
  **/
  @ApiModelProperty(example = "null", value = "")
  public ReportTypeEnum getReportType() {
    return reportType;
  }

  public void setReportType(ReportTypeEnum reportType) {
    this.reportType = reportType;
  }

  public ReportCapabilityDescriptionDto rid(String rid) {
    this.rid = rid;
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRid() {
    return rid;
  }

  public void setRid(String rid) {
    this.rid = rid;
  }

  public ReportCapabilityDescriptionDto siScaleCode(SiScaleCodeEnum siScaleCode) {
    this.siScaleCode = siScaleCode;
    return this;
  }

   /**
   * Get siScaleCode
   * @return siScaleCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public SiScaleCodeEnum getSiScaleCode() {
    return siScaleCode;
  }

  public void setSiScaleCode(SiScaleCodeEnum siScaleCode) {
    this.siScaleCode = siScaleCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportCapabilityDescriptionDto reportCapabilityDescriptionDto = (ReportCapabilityDescriptionDto) o;
    return Objects.equals(this.id, reportCapabilityDescriptionDto.id) &&
        Objects.equals(this.itemDescription, reportCapabilityDescriptionDto.itemDescription) &&
        Objects.equals(this.itemUnits, reportCapabilityDescriptionDto.itemUnits) &&
        Objects.equals(this.oadrMaxPeriod, reportCapabilityDescriptionDto.oadrMaxPeriod) &&
        Objects.equals(this.oadrMinPeriod, reportCapabilityDescriptionDto.oadrMinPeriod) &&
        Objects.equals(this.oadrOnChange, reportCapabilityDescriptionDto.oadrOnChange) &&
        Objects.equals(this.readingType, reportCapabilityDescriptionDto.readingType) &&
        Objects.equals(this.reportType, reportCapabilityDescriptionDto.reportType) &&
        Objects.equals(this.rid, reportCapabilityDescriptionDto.rid) &&
        Objects.equals(this.siScaleCode, reportCapabilityDescriptionDto.siScaleCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, itemDescription, itemUnits, oadrMaxPeriod, oadrMinPeriod, oadrOnChange, readingType, reportType, rid, siScaleCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportCapabilityDescriptionDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    itemDescription: ").append(toIndentedString(itemDescription)).append("\n");
    sb.append("    itemUnits: ").append(toIndentedString(itemUnits)).append("\n");
    sb.append("    oadrMaxPeriod: ").append(toIndentedString(oadrMaxPeriod)).append("\n");
    sb.append("    oadrMinPeriod: ").append(toIndentedString(oadrMinPeriod)).append("\n");
    sb.append("    oadrOnChange: ").append(toIndentedString(oadrOnChange)).append("\n");
    sb.append("    readingType: ").append(toIndentedString(readingType)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("    siScaleCode: ").append(toIndentedString(siScaleCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

