/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * VenDemandResponseEventDto
 */

public class VenDemandResponseEventDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("eventId")
  private String eventId = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("lastSentModificationNumber")
  private Long lastSentModificationNumber = null;

  @SerializedName("lastUpdateDatetime")
  private Long lastUpdateDatetime = null;

  @SerializedName("venId")
  private String venId = null;

  /**
   * Gets or Sets venOpt
   */
  public enum VenOptEnum {
    @SerializedName("OPT_IN")
    IN("OPT_IN"),
    
    @SerializedName("OPT_OUT")
    OUT("OPT_OUT");

    private String value;

    VenOptEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("venOpt")
  private VenOptEnum venOpt = null;

  public VenDemandResponseEventDto eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public VenDemandResponseEventDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public VenDemandResponseEventDto lastSentModificationNumber(Long lastSentModificationNumber) {
    this.lastSentModificationNumber = lastSentModificationNumber;
    return this;
  }

   /**
   * Get lastSentModificationNumber
   * @return lastSentModificationNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLastSentModificationNumber() {
    return lastSentModificationNumber;
  }

  public void setLastSentModificationNumber(Long lastSentModificationNumber) {
    this.lastSentModificationNumber = lastSentModificationNumber;
  }

  public VenDemandResponseEventDto lastUpdateDatetime(Long lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(Long lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }

  public VenDemandResponseEventDto venId(String venId) {
    this.venId = venId;
    return this;
  }

   /**
   * Get venId
   * @return venId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVenId() {
    return venId;
  }

  public void setVenId(String venId) {
    this.venId = venId;
  }

  public VenDemandResponseEventDto venOpt(VenOptEnum venOpt) {
    this.venOpt = venOpt;
    return this;
  }

   /**
   * Get venOpt
   * @return venOpt
  **/
  @ApiModelProperty(example = "null", value = "")
  public VenOptEnum getVenOpt() {
    return venOpt;
  }

  public void setVenOpt(VenOptEnum venOpt) {
    this.venOpt = venOpt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenDemandResponseEventDto venDemandResponseEventDto = (VenDemandResponseEventDto) o;
    return Objects.equals(this.eventId, venDemandResponseEventDto.eventId) &&
        Objects.equals(this.id, venDemandResponseEventDto.id) &&
        Objects.equals(this.lastSentModificationNumber, venDemandResponseEventDto.lastSentModificationNumber) &&
        Objects.equals(this.lastUpdateDatetime, venDemandResponseEventDto.lastUpdateDatetime) &&
        Objects.equals(this.venId, venDemandResponseEventDto.venId) &&
        Objects.equals(this.venOpt, venDemandResponseEventDto.venOpt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventId, id, lastSentModificationNumber, lastUpdateDatetime, venId, venOpt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenDemandResponseEventDto {\n");
    
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSentModificationNumber: ").append(toIndentedString(lastSentModificationNumber)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("    venId: ").append(toIndentedString(venId)).append("\n");
    sb.append("    venOpt: ").append(toIndentedString(venOpt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

