/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * VenOptDto
 */

public class VenOptDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("end")
  private Long end = null;

  @SerializedName("eventId")
  private String eventId = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("marketContext")
  private String marketContext = null;

  /**
   * Gets or Sets opt
   */
  public enum OptEnum {
    @SerializedName("OPT_IN")
    IN("OPT_IN"),
    
    @SerializedName("OPT_OUT")
    OUT("OPT_OUT");

    private String value;

    OptEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("opt")
  private OptEnum opt = null;

  @SerializedName("optId")
  private String optId = null;

  @SerializedName("resourceId")
  private Long resourceId = null;

  @SerializedName("start")
  private Long start = null;

  @SerializedName("venId")
  private String venId = null;

  public VenOptDto end(Long end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEnd() {
    return end;
  }

  public void setEnd(Long end) {
    this.end = end;
  }

  public VenOptDto eventId(String eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public VenOptDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public VenOptDto marketContext(String marketContext) {
    this.marketContext = marketContext;
    return this;
  }

   /**
   * Get marketContext
   * @return marketContext
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMarketContext() {
    return marketContext;
  }

  public void setMarketContext(String marketContext) {
    this.marketContext = marketContext;
  }

  public VenOptDto opt(OptEnum opt) {
    this.opt = opt;
    return this;
  }

   /**
   * Get opt
   * @return opt
  **/
  @ApiModelProperty(example = "null", value = "")
  public OptEnum getOpt() {
    return opt;
  }

  public void setOpt(OptEnum opt) {
    this.opt = opt;
  }

  public VenOptDto optId(String optId) {
    this.optId = optId;
    return this;
  }

   /**
   * Get optId
   * @return optId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOptId() {
    return optId;
  }

  public void setOptId(String optId) {
    this.optId = optId;
  }

  public VenOptDto resourceId(Long resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResourceId() {
    return resourceId;
  }

  public void setResourceId(Long resourceId) {
    this.resourceId = resourceId;
  }

  public VenOptDto start(Long start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStart() {
    return start;
  }

  public void setStart(Long start) {
    this.start = start;
  }

  public VenOptDto venId(String venId) {
    this.venId = venId;
    return this;
  }

   /**
   * Get venId
   * @return venId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVenId() {
    return venId;
  }

  public void setVenId(String venId) {
    this.venId = venId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenOptDto venOptDto = (VenOptDto) o;
    return Objects.equals(this.end, venOptDto.end) &&
        Objects.equals(this.eventId, venOptDto.eventId) &&
        Objects.equals(this.id, venOptDto.id) &&
        Objects.equals(this.marketContext, venOptDto.marketContext) &&
        Objects.equals(this.opt, venOptDto.opt) &&
        Objects.equals(this.optId, venOptDto.optId) &&
        Objects.equals(this.resourceId, venOptDto.resourceId) &&
        Objects.equals(this.start, venOptDto.start) &&
        Objects.equals(this.venId, venOptDto.venId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(end, eventId, id, marketContext, opt, optId, resourceId, start, venId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenOptDto {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    marketContext: ").append(toIndentedString(marketContext)).append("\n");
    sb.append("    opt: ").append(toIndentedString(opt)).append("\n");
    sb.append("    optId: ").append(toIndentedString(optId)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    venId: ").append(toIndentedString(venId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

