/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.avob.server.oadrvtn20b.model.VenReportCapabilityDto;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * VenReportDto
 */

public class VenReportDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("capabilities")
  private List<VenReportCapabilityDto> capabilities = new ArrayList<VenReportCapabilityDto>();

  @SerializedName("id")
  private Long id = null;

  @SerializedName("username")
  private String username = null;

  public VenReportDto capabilities(List<VenReportCapabilityDto> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public VenReportDto addCapabilitiesItem(VenReportCapabilityDto capabilitiesItem) {
    this.capabilities.add(capabilitiesItem);
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<VenReportCapabilityDto> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<VenReportCapabilityDto> capabilities) {
    this.capabilities = capabilities;
  }

  public VenReportDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public VenReportDto username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenReportDto venReportDto = (VenReportDto) o;
    return Objects.equals(this.capabilities, venReportDto.capabilities) &&
        Objects.equals(this.id, venReportDto.id) &&
        Objects.equals(this.username, venReportDto.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capabilities, id, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenReportDto {\n");
    
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

