/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * VenUpdateDto
 */

public class VenUpdateDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pullFrequencySeconds")
  private Long pullFrequencySeconds = null;

  public VenUpdateDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VenUpdateDto pullFrequencySeconds(Long pullFrequencySeconds) {
    this.pullFrequencySeconds = pullFrequencySeconds;
    return this;
  }

   /**
   * Get pullFrequencySeconds
   * @return pullFrequencySeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPullFrequencySeconds() {
    return pullFrequencySeconds;
  }

  public void setPullFrequencySeconds(Long pullFrequencySeconds) {
    this.pullFrequencySeconds = pullFrequencySeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenUpdateDto venUpdateDto = (VenUpdateDto) o;
    return Objects.equals(this.name, venUpdateDto.name) &&
        Objects.equals(this.pullFrequencySeconds, venUpdateDto.pullFrequencySeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, pullFrequencySeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenUpdateDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pullFrequencySeconds: ").append(toIndentedString(pullFrequencySeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

