/*
 * Avob VTN Rest API
 * Description
 *
 * OpenAPI spec version: API TOS
 * Contact: bzanni@avob.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.avob.server.oadrvtn20b.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * VtnConfigurationDto
 */

public class VtnConfigurationDto implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("contextPath")
  private String contextPath = null;

  @SerializedName("host")
  private String host = null;

  @SerializedName("oadrVersion")
  private String oadrVersion = null;

  @SerializedName("port")
  private Integer port = null;

  @SerializedName("pullFrequencySeconds")
  private Long pullFrequencySeconds = null;

  @SerializedName("saveVenDate")
  private Boolean saveVenDate = null;

  @SerializedName("supportCertificateGeneration")
  private Boolean supportCertificateGeneration = null;

  @SerializedName("supportPush")
  private Boolean supportPush = null;

  @SerializedName("supportUnsecuredHttpPush")
  private Boolean supportUnsecuredHttpPush = null;

  @SerializedName("vtnId")
  private String vtnId = null;

  @SerializedName("xmlSignatureReplayProtectSecond")
  private Long xmlSignatureReplayProtectSecond = null;

  @SerializedName("xsdValidation")
  private Boolean xsdValidation = null;

  public VtnConfigurationDto contextPath(String contextPath) {
    this.contextPath = contextPath;
    return this;
  }

   /**
   * Get contextPath
   * @return contextPath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContextPath() {
    return contextPath;
  }

  public void setContextPath(String contextPath) {
    this.contextPath = contextPath;
  }

  public VtnConfigurationDto host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public VtnConfigurationDto oadrVersion(String oadrVersion) {
    this.oadrVersion = oadrVersion;
    return this;
  }

   /**
   * Get oadrVersion
   * @return oadrVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOadrVersion() {
    return oadrVersion;
  }

  public void setOadrVersion(String oadrVersion) {
    this.oadrVersion = oadrVersion;
  }

  public VtnConfigurationDto port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public VtnConfigurationDto pullFrequencySeconds(Long pullFrequencySeconds) {
    this.pullFrequencySeconds = pullFrequencySeconds;
    return this;
  }

   /**
   * Get pullFrequencySeconds
   * @return pullFrequencySeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPullFrequencySeconds() {
    return pullFrequencySeconds;
  }

  public void setPullFrequencySeconds(Long pullFrequencySeconds) {
    this.pullFrequencySeconds = pullFrequencySeconds;
  }

  public VtnConfigurationDto saveVenDate(Boolean saveVenDate) {
    this.saveVenDate = saveVenDate;
    return this;
  }

   /**
   * Get saveVenDate
   * @return saveVenDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSaveVenDate() {
    return saveVenDate;
  }

  public void setSaveVenDate(Boolean saveVenDate) {
    this.saveVenDate = saveVenDate;
  }

  public VtnConfigurationDto supportCertificateGeneration(Boolean supportCertificateGeneration) {
    this.supportCertificateGeneration = supportCertificateGeneration;
    return this;
  }

   /**
   * Get supportCertificateGeneration
   * @return supportCertificateGeneration
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSupportCertificateGeneration() {
    return supportCertificateGeneration;
  }

  public void setSupportCertificateGeneration(Boolean supportCertificateGeneration) {
    this.supportCertificateGeneration = supportCertificateGeneration;
  }

  public VtnConfigurationDto supportPush(Boolean supportPush) {
    this.supportPush = supportPush;
    return this;
  }

   /**
   * Get supportPush
   * @return supportPush
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSupportPush() {
    return supportPush;
  }

  public void setSupportPush(Boolean supportPush) {
    this.supportPush = supportPush;
  }

  public VtnConfigurationDto supportUnsecuredHttpPush(Boolean supportUnsecuredHttpPush) {
    this.supportUnsecuredHttpPush = supportUnsecuredHttpPush;
    return this;
  }

   /**
   * Get supportUnsecuredHttpPush
   * @return supportUnsecuredHttpPush
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSupportUnsecuredHttpPush() {
    return supportUnsecuredHttpPush;
  }

  public void setSupportUnsecuredHttpPush(Boolean supportUnsecuredHttpPush) {
    this.supportUnsecuredHttpPush = supportUnsecuredHttpPush;
  }

  public VtnConfigurationDto vtnId(String vtnId) {
    this.vtnId = vtnId;
    return this;
  }

   /**
   * Get vtnId
   * @return vtnId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVtnId() {
    return vtnId;
  }

  public void setVtnId(String vtnId) {
    this.vtnId = vtnId;
  }

  public VtnConfigurationDto xmlSignatureReplayProtectSecond(Long xmlSignatureReplayProtectSecond) {
    this.xmlSignatureReplayProtectSecond = xmlSignatureReplayProtectSecond;
    return this;
  }

   /**
   * Get xmlSignatureReplayProtectSecond
   * @return xmlSignatureReplayProtectSecond
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getXmlSignatureReplayProtectSecond() {
    return xmlSignatureReplayProtectSecond;
  }

  public void setXmlSignatureReplayProtectSecond(Long xmlSignatureReplayProtectSecond) {
    this.xmlSignatureReplayProtectSecond = xmlSignatureReplayProtectSecond;
  }

  public VtnConfigurationDto xsdValidation(Boolean xsdValidation) {
    this.xsdValidation = xsdValidation;
    return this;
  }

   /**
   * Get xsdValidation
   * @return xsdValidation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getXsdValidation() {
    return xsdValidation;
  }

  public void setXsdValidation(Boolean xsdValidation) {
    this.xsdValidation = xsdValidation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VtnConfigurationDto vtnConfigurationDto = (VtnConfigurationDto) o;
    return Objects.equals(this.contextPath, vtnConfigurationDto.contextPath) &&
        Objects.equals(this.host, vtnConfigurationDto.host) &&
        Objects.equals(this.oadrVersion, vtnConfigurationDto.oadrVersion) &&
        Objects.equals(this.port, vtnConfigurationDto.port) &&
        Objects.equals(this.pullFrequencySeconds, vtnConfigurationDto.pullFrequencySeconds) &&
        Objects.equals(this.saveVenDate, vtnConfigurationDto.saveVenDate) &&
        Objects.equals(this.supportCertificateGeneration, vtnConfigurationDto.supportCertificateGeneration) &&
        Objects.equals(this.supportPush, vtnConfigurationDto.supportPush) &&
        Objects.equals(this.supportUnsecuredHttpPush, vtnConfigurationDto.supportUnsecuredHttpPush) &&
        Objects.equals(this.vtnId, vtnConfigurationDto.vtnId) &&
        Objects.equals(this.xmlSignatureReplayProtectSecond, vtnConfigurationDto.xmlSignatureReplayProtectSecond) &&
        Objects.equals(this.xsdValidation, vtnConfigurationDto.xsdValidation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextPath, host, oadrVersion, port, pullFrequencySeconds, saveVenDate, supportCertificateGeneration, supportPush, supportUnsecuredHttpPush, vtnId, xmlSignatureReplayProtectSecond, xsdValidation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VtnConfigurationDto {\n");
    
    sb.append("    contextPath: ").append(toIndentedString(contextPath)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    oadrVersion: ").append(toIndentedString(oadrVersion)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    pullFrequencySeconds: ").append(toIndentedString(pullFrequencySeconds)).append("\n");
    sb.append("    saveVenDate: ").append(toIndentedString(saveVenDate)).append("\n");
    sb.append("    supportCertificateGeneration: ").append(toIndentedString(supportCertificateGeneration)).append("\n");
    sb.append("    supportPush: ").append(toIndentedString(supportPush)).append("\n");
    sb.append("    supportUnsecuredHttpPush: ").append(toIndentedString(supportUnsecuredHttpPush)).append("\n");
    sb.append("    vtnId: ").append(toIndentedString(vtnId)).append("\n");
    sb.append("    xmlSignatureReplayProtectSecond: ").append(toIndentedString(xmlSignatureReplayProtectSecond)).append("\n");
    sb.append("    xsdValidation: ").append(toIndentedString(xsdValidation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

